# Generated by Django 3.1.5 on 2022-05-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='fechamento_ajustado',
            field=models.CharField(blank=True, default=0.0, max_length=255),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='status_fechado_aberto',
            field=models.CharField(blank=True, default='Aguardando Atualizacao', max_length=255),
        ),
    ]
