# Generated by Django 3.2.18 on 2023-05-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230326_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='total_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Total Custo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='proventos',
            name='tipo_provento',
            field=models.CharField(choices=[('D', 'DIVIDENDOS'), ('J', 'JUROS COMPOSTO'), ('R', 'RENDIMENTOS')], max_length=250),
        ),
    ]
