# Generated by Django 3.1.5 on 2021-01-10 00:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(blank=True, max_length=255)),
                ('ativo', models.CharField(blank=True, max_length=255, unique=True)),
                ('fechamento_ajustado', models.CharField(blank=True, max_length=255)),
                ('variacao_1', models.CharField(blank=True, default=0.0, max_length=255)),
                ('variacao_2', models.CharField(blank=True, default=0.0, max_length=255)),
                ('status_fechado_aberto', models.CharField(blank=True, max_length=255)),
                ('data_instante', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=250)),
                ('tipo_provento', models.CharField(choices=[('D', 'DIVIDENDOS'), ('J', 'JUROS COMPOSTO')], max_length=250)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA')], max_length=50)),
                ('total_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Total Compra')),
                ('identificador', models.CharField(max_length=50)),
                ('corretagem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emolumentos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Emolumento B3')),
                ('tx_liquida_CBLC', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxa Líquida CBLC')),
                ('IRRF_Final', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='IRRF Final')),
                ('Lucro_Day_Trade', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Lucro Day Trade')),
                ('IRRF_Day_Trade', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='IRRF Day Trade')),
                ('total_custo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Total Compra')),
                ('corretora', models.CharField(blank=True, max_length=250)),
                ('data_instante', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=250)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
